wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.19.8
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751540039
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 4
      - 13
      - 23
      - 42
      - 55
      4: 3.13.2
      5: 0.19.8
      6: 4.49.0
      8:
      - 5
      13: linux-x86_64
